import "./globals.css";
import { Srisakdi } from "next/font/google"; // เปลี่ยนเป็น Srisakdi
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import BootstrapClient from "./components/BootstrapClient";

// กำหนดฟอนต์ Srisakdi แบบตัวหนา
const srisakdi = Srisakdi({
  subsets: ["thai", "latin"],
  weight: ["700"], // 700 = ตัวหนา
  display: "swap",
});

export const metadata = {
  title: "ผจญภัย",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={srisakdi.className}>
        <Navbar />
        {children}
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
