// app/layout.js
import './globals.css';
import { Prompt } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const prompt = Prompt({
  subsets: ['thai', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});


export const metadata = {
  title: 'ผจญภัย',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={prompt.className}>

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
